language: cpp

dist: xerus

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - libcilkrts5
    - cmake
    - cmake-data

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake .. && make -j
