language: cpp

dist: trusty
sudo: required

addons:
  apt:
    packages:
    - cmake
    - git
    - make

after_success:
  - $CC --version
  - git clone https://bitbucket.org/intelcilkruntime/intel-cilk-runtime.git && cd intel-cilk-runtime
  - libtoolize
  - aclocal
  - automake --add-missing
  - autoconf
  - ./configure
  - make -j
  - sudo make install -j
  - cd ..
  - rm -rf intel-cilk-runtime

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j
  - sudo make -j install
  - cd ..
  - export CC="clang"
  - export CXX="clang++"
