language: cpp

dist: trusty
sudo: required

addons:
  apt:
    packages:
    - git
    - make
    - tar

before_install:
  - wget https://cmake.org/files/v3.7/cmake-3.7.2.tar.gz
  - tar -xzf cmake-3.7.2.tar.gz
  - cd cmake-3.7.2
  - ./bootstrap
  - make
  - sudo make install
  - cd ..
  - rm -rf cmake-3.7.2
  - echo "Ending pre install" && pwd

after_success:
  - $CC --version
  - git clone https://bitbucket.org/intelcilkruntime/intel-cilk-runtime.git && cd intel-cilk-runtime
  - libtoolize
  - aclocal
  - automake --add-missing
  - autoconf
  - ./configure
  - make
  - sudo make install
  - cd ..
  - rm -rf intel-cilk-runtime

compiler:
  - clang
  - gcc

script:
  - cd tools && git clone https://github.com/wsmoses/Cilk-Clang clang && cd ..
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ..
  - export CC="clang"
  - export CXX="clang++"
